### PR TITLE
exclude clojure get and await - raises warnings.

### PR DESCRIPTION
**Pull request by andreiursan**
I think the PR's title is self explanatory.

### CODE REVIEW

**Comment by circlespainter** [comment]
Thanks!

**Comment by andreiursan** [comment]
my pleasure.
any info for when 0.6.0 will be released?

**Comment by circlespainter** [comment]
[0.6.0 has been released already](http://blog.paralleluniverse.co/2016/02/10/comsat-0.6.0/), are you asking because you'd like to be able to fetch an artifact including this improvement from a mvn repository?

**Comment by andreiursan** [comment]
@circlespainter yes. It would be great if it would be available in one of the public mavens or in clojars.
Leiningen can resolve 0.5.0 but not 0.6.0.

**Comment by pron** [comment]
@andreiursan Done. Sorry, it was an oversight on my part. I forgot that the Clojure artifacts need to be published separately.

**Comment by andreiursan** [comment]
@pron thank you :)

**Pull request merged**
