### PR TITLE
HttpMessage header name case normalization 

### PR DESCRIPTION
**Pull request by roded**
https://github.com/puniverse/comsat/pull/66

I seem to have forgot `HttpRequest.Builder` last time.
Do tell if I missed anything.
(why is this not automatically mergeable though?)

### CODE REVIEW

**Comment by roded** [comment]
Umph.. git is troubling me.
My release seems not updated for some reason.

**Comment by roded** [comment]
That's that hopefully.

**Comment by circlespainter** [comment]
Thanks!

**Comment by roded** [comment]
Sure.
Sorry for the mess.

**Comment by roded** [comment]
Also, can you say when the SNAPSHOT will be available? I'd like to update my code to use this.

**Comment by circlespainter** [comment]
Actually we'll write somewhere upon which branches one should base fix VS. feature PRs.

You're using `master` features though, right?

**Comment by roded** [comment]
In the above question, I meant the SNAPSHOT deployed to sonatype.

I'll use whatever branch you'll say so.

**Comment by circlespainter** [comment]
I'm uploading a `SNAPSHOT` built from `master` after merging in `release` so it'll contain both fixes and new features so far. You should be able to download it in ten minutes or so.

**Comment by circlespainter** [comment]
I'm having some connectivity problems while uploading to SonaType so I'll retry later. Anyway, you can build and install locally from `master` in the meanwhile.

**Pull request merged**
