### PR TITLE
Undertow Web Actors: support fallback HttpHandler

### PR DESCRIPTION
**Pull request by roded**

### CODE REVIEW

**Comment by circlespainter** [comment]
A `40x` status could be produced by an actor as well, could you handle this case too? Also, I prefer to set non-private methods `final` unless there's a reason not to.

**Comment by roded** [comment]
Sorry, I don't follow; is that not handled by HttpActorAdapter?

**Comment by circlespainter** [comment]
`HttpActorAdapter.handleReply` will send a response in case there's an error status; instead, with chaining and if the statux it is `40x`, it should really invoke the next handler (if there is one).

**Comment by roded** [comment]
Though, are not client error statuses considered an attempt at handling and should be thus promptly return to the user?

**Comment by circlespainter** [comment]
True; I also think that the method (and field) name should probably be something like `setFallbackHandler` because `setNextHandler` could suggest that it is always called, like it can happen f.e. in a Netty pipeline.

**Comment by circlespainter** [comment]
Looks good, thanks!

**Pull request merged**
